# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_tprod_A_X_Bt <- function(X, A, B) {
    .Call(`_sir_cpp_tprod_A_X_Bt`, X, A, B)
}

cpp_amprod_W_v <- function(W, v) {
    .Call(`_sir_cpp_amprod_W_v`, W, v)
}

#' Construct Wbeta design matrix for ALS update (theta, alpha)
#'
#' Efficiently calculates and flattens the Wbeta component of the design matrix.
#' Wbeta[,,k,t] corresponds to W[,,k] %*% X[,,t] %*% (W*beta)^T.
#'
#' @param W (m x m x p) array of influence covariates.
#' @param X (m x m x T) array, typically lagged outcomes.
#' @param beta (p x 1) vector of current beta estimates.
#' @return (m*m*T) x p matrix for the GLM design matrix.
cpp_construct_Wbeta_design <- function(W, X, beta) {
    .Call(`_sir_cpp_construct_Wbeta_design`, W, X, beta)
}

#' Construct Walpha design matrix for ALS update (theta, beta)
#'
#' Efficiently calculates and flattens the Walpha component of the design matrix.
#' Walpha[,,k,t] corresponds to (W*alpha) %*% X[,,t] %*% W[,,k]^T.
#'
#' @param W (m x m x p) array of influence covariates.
#' @param X (m x m x T) array, typically lagged outcomes.
#' @param alpha (p x 1) vector of current alpha estimates.
#' @return (m*m*T) x p matrix for the GLM design matrix.
cpp_construct_Walpha_design <- function(W, X, alpha) {
    .Call(`_sir_cpp_construct_Walpha_design`, W, X, alpha)
}

#' Calculate Gradient and Hessian for SIR models (NLL)
#'
#' Computes the gradient, Hessian, and score cross-product for the Negative Log-Likelihood (NLL)
#' of the SIR model. This implementation is optimized by avoiding explicit calculation of Xij
#' inside the loops, relying instead on the (A, B) structure.
#'
#' @param tab Parameter vector (theta, alpha[-1], beta).
#' @param Y (m x m x T) array of outcomes.
#' @param W (m x m x p) array of influence covariates.
#' @param X (m x m x T) array for the bilinear part.
#' @param Z_list List of q (m x m x T) arrays for exogenous covariates (passed this way for 4D handling).
#' @param family Distribution family ("poisson", "normal", "binomial").
#' @return A list containing the gradient (grad), Hessian (hess), and score cross-product (shess) of the NLL.
cpp_mll_gH <- function(tab, Y, W, X, Z_list, family) {
    .Call(`_sir_cpp_mll_gH`, tab, Y, W, X, Z_list, family)
}

