name: Build sir Release Binaries

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux
          - os: macos-13
            label: macos-intel
          - os: macos-15
            label: macos-arm64
          - os: macos-latest
            label: macos-latest
          - os: windows-latest
            label: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install system dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install rtools -y --no-progress
          echo "C:\rtools43\usr\bin;C:\rtools43\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::Rcpp
            any::RcppArmadillo
            any::devtools
            any::testthat

      - name: Extract version from DESCRIPTION
        id: version
        run: |
          version <- read.dcf("DESCRIPTION")[1, "Version"]
          cat(sprintf("version=%s\n", version), file = Sys.getenv("GITHUB_OUTPUT"), append = TRUE)
        shell: Rscript {0}

      - name: Build source package
        run: R CMD build .
        shell: bash

      - name: Build binary package
        run: |
          pkg_file=$(ls -1tr *.tar.gz | tail -n 1)
          R CMD INSTALL --build "$pkg_file"
          
          platform=${{ matrix.label }}
          for f in *.tgz *.zip *.tar.gz *.tar.bz2; do
            if [ -f "$f" ]; then
              ext="${f##*.}"
              filename=$(basename "$f")
              newname="sir_${{ steps.version.outputs.version }}_${platform}.${ext}"
              mv "$f" "$newname"
              echo "Created: $newname"
            fi
          done
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sir-${{ matrix.label }}-v${{ steps.version.outputs.version }}
          path: |
            *.tgz
            *.zip
            *.tar.gz
          retention-days: 90

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move artifacts to root of artifacts directory
        run: |
          find artifacts -type f \( -name "*.zip" -o -name "*.tgz" -o -name "*.tar.gz" \) -exec mv {} artifacts/ \;
          ls -la artifacts/
        shell: bash

      - name: Extract version from DESCRIPTION
        id: version
        run: |
          version <- read.dcf("DESCRIPTION")[1, "Version"]
          cat(sprintf("version=%s\n", version), file = Sys.getenv("GITHUB_OUTPUT"), append = TRUE)
        shell: Rscript {0}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "sir v${{ steps.version.outputs.version }}"
          tag_name: "v${{ steps.version.outputs.version }}"
          body: |
            ## Social Influence Regression (SIR) Package v${{ steps.version.outputs.version }}
            
            This release includes pre-built binaries for multiple platforms.
            
            ### Installation
            
            To install from a binary package, download the appropriate file for your platform and run:
            
            ```r
            # For Windows (.zip):
            install.packages("sir_${{ steps.version.outputs.version }}_windows.zip", repos = NULL, type = "binary")
            
            # For macOS (.tgz):
            install.packages("sir_${{ steps.version.outputs.version }}_macos-arm64.tgz", repos = NULL, type = "binary")
            
            # For source package (.tar.gz):
            install.packages("sir_${{ steps.version.outputs.version }}_linux.tar.gz", repos = NULL, type = "source")
            ```
            
            ### Package Features
            - Social Influence Regression models for network data
            - Support for Poisson, Normal, and Binomial distributions
            - Alternating Least Squares (ALS) and direct optimization methods
            - Optimized C++ implementation using RcppArmadillo
            - Comprehensive S3 methods and ggplot2 visualizations
            
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            artifacts/*.tgz
            artifacts/*.zip
            artifacts/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}